/**
 * The service catalogue (§3 of the growth strategy), one entry per published
 * service page.
 *
 * Every entry carries the four blocks the document insists on for each
 * service - what DriveMe includes, what the customer must arrange and pay,
 * what is not included, and the implementation note the developer/operations
 * side has to honour - plus the §10 page skeleton (steps, price, FAQ,
 * related links).
 *
 * `gate` names an entry in site.mjs `launchGates`. While that gate is not
 * live, the page renders the "awaiting clearance" notice instead of a booking
 * CTA and the booking flow refuses to take the job. That is the document's
 * implementation principle in code: no published promise without an
 * operational reality behind it.
 *
 * `category`:
 *   'concierge' - Take care of my car (primary growth category)
 *   'driver'    - I need a driver (premium passenger category)
 *   'business'  - B2B, lead form rather than instant checkout
 */

export const services = [
  /* ------------------------------------------------------------------ */
  {
    key: 'inspection',
    category: 'concierge',
    launch: 'priority',
    appointment: 'required',
    icon: 'inspection',
    price: { key: 'inspection' },
    related: ['workshop', 'tyre', 'pickupReturn'],
    // §3.1 implementation note - operational, kept in the page source as a
    // comment for whoever maintains it.
    devNote: 'If the vehicle fails but may legally be driven, DriveMe can return it as instructed. If driving is prohibited, the job pauses and the customer must arrange towing or another legal transport method.',
    fi: {
      slug: 'auton-vienti-katsastukseen',
      nav: 'Auton vienti katsastukseen',
      short: 'Katsastus',
      title: 'Auton vienti katsastukseen | Nouto ja palautus | DriveMe',
      description: 'DriveMe noutaa autosi, vie sen ennalta varattuun katsastukseen ja palauttaa sen sovitusti. Katsastusmaksu maksetaan suoraan asemalle.',
      h1: 'Auton vienti katsastukseen ilman oman aikasi menettämistä',
      lead: 'Oletko jo varannut katsastusajan? Noudamme ajokuntoisen autosi, viemme sen asemalle ja palautamme sen katsastusdokumenttien kanssa.',
      keywords: ['auton vienti katsastukseen', 'katsastus noutopalvelu', 'auton käyttö katsastuksessa'],
      steps: [
        'Varaat katsastusajan valitsemaltasi asemalta ja lähetät meille aseman, ajan ja varausnumeron.',
        'Nouto sovitussa aikaikkunassa: dokumentoimme kunnon, mittarilukeman ja polttoaine- tai lataustason.',
        'Kuljettaja luovuttaa auton asemalle ja kuittaa luovutuksen.',
        'Palautamme auton sovittuun osoitteeseen katsastusdokumenttien kanssa ja kuittaamme toimituksen.',
      ],
      included: [
        'Sovittu noutoaikaikkuna',
        'Noudon kuntokuvat, mittarilukema ja polttoaine- tai lataustaso',
        'Ajo asiakkaan vahvistamalle katsastusasemalle',
        'Luovutus, valitun tuotteen mukainen kohtuullinen odotus, palautus ja valmistumiskuittaus',
      ],
      customer: [
        'Varaa ja vahvista katsastusaika ennen kuljettajan lähtöä',
        'Ilmoita DriveMelle asema, aika ja varausnumero',
        'Maksa katsastusasemalle suoraan',
        'Varmista, että auto on laillinen, rekisteröity, vakuutettu, ajokuntoinen ja riittävästi tankattu tai ladattu',
      ],
      excluded: [
        'Katsastusmaksu, päästömittaus tai jälkitarkastus',
        'Korjaukset, vianmääritys tai neuvonta',
        'Takuu siitä, että auto läpäisee katsastuksen',
        'Ajokieltoon määrätyn ajoneuvon ajaminen',
      ],
      boundary: 'Asiakas varaa ja maksaa katsastuksen suoraan asemalle. DriveMe vastaa sovitusta nouto-, ajo-, toimitus- ja luovutuspalvelusta, ei katsastuksen sisällöstä tai lopputuloksesta.',
      faq: [
        { q: 'Voiko joku muu viedä autoni katsastukseen?', a: 'Kyllä. Katsastusasemalle voi tuoda auton kuka tahansa, jolla on ajo-oikeus ja auton avaimet. Sinun ei tarvitse olla paikalla. Katsastusmaksu maksetaan asemalle suoraan, ja asema toimittaa dokumentit auton mukana.' },
        { q: 'Mitä tapahtuu, jos auto ei läpäise katsastusta?', a: 'Jos autoa saa yhä laillisesti ajaa, palautamme sen ohjeidesi mukaan tai viemme sen sovittuun korjaamoon. Jos auto määrätään ajokieltoon, keskeytämme työn ja sovimme kanssasi hinauksesta tai muusta lainmukaisesta kuljetuksesta - emme aja ajokiellossa olevaa autoa.' },
        { q: 'Tarvitseeko katsastusaika olla varattuna etukäteen?', a: 'Kyllä. Emme lähetä kuljettajaa ilman vahvistettua aikaa, koska ilman sitä emme voi luvata autolle sisäänottoa emmekä palautusaikaa.' },
        { q: 'Kuka maksaa katsastuksen?', a: 'Sinä maksat asemalle suoraan. DriveMe-palkkio kattaa vain noudon, ajon, luovutuksen ja palautuksen.' },
        { q: 'Mitä autossa pitää olla mukana?', a: 'Riittävästi polttoainetta tai latausta, oikeat kausirenkaat ja mahdollinen lukkopulttiavain. Ota arvoesineet pois autosta ennen noutoa.' },
      ],
    },
    en: {
      slug: 'car-to-inspection',
      nav: 'Vehicle inspection run',
      short: 'Inspection',
      title: 'Vehicle inspection run | Pickup and return | DriveMe',
      description: 'DriveMe collects your car, takes it to your pre-booked inspection and returns it as agreed. The inspection fee is paid directly to the station.',
      h1: 'Your car goes to its inspection, your day stays yours',
      lead: 'Already booked the inspection? We collect your roadworthy car, take it to the station and return it with the inspection documents.',
      keywords: ['vehicle inspection pickup', 'car inspection collection Helsinki'],
      steps: [
        'You book the inspection with your chosen station and send us the station, time and booking reference.',
        'Collection within the agreed window: we document condition, mileage and fuel or charge level.',
        'The driver hands the car over at the station and records the handover.',
        'We return the car to the agreed address with the inspection documents and confirm completion.',
      ],
      included: [
        'Scheduled collection window',
        'Collection condition photos, mileage and fuel/charge record',
        'Driving to the customer’s confirmed inspection station',
        'Handover, reasonable waiting under the selected product, return and completion record',
      ],
      customer: [
        'Book and confirm the inspection before the driver is sent',
        'Give DriveMe the station, time and booking reference',
        'Pay the inspection station directly',
        'Ensure the vehicle is legal, registered, insured, roadworthy and sufficiently fuelled or charged',
      ],
      excluded: [
        'Inspection fee, emissions measurement or follow-up inspection',
        'Repairs, diagnostics or advice',
        'A guarantee that the car will pass',
        'Driving a vehicle that is placed under a driving ban',
      ],
      boundary: 'The customer books and pays the inspection station directly. DriveMe is responsible for the agreed collection, driving, delivery and handover service, not for the content or outcome of the inspection.',
      faq: [
        { q: 'Can someone else take my car to its inspection?', a: 'Yes. Anyone with a valid licence and the keys can present the car. You do not need to be there. The inspection fee is paid at the station and the documents travel back with the car.' },
        { q: 'What happens if the car fails?', a: 'If it may still legally be driven, we return it as you instruct or take it to an agreed workshop. If it is placed under a driving ban we pause the job and agree towing or another legal transport with you - we do not drive a banned vehicle.' },
        { q: 'Does the inspection need to be booked in advance?', a: 'Yes. We do not send a driver without a confirmed slot, because without one we cannot promise intake or a return time.' },
        { q: 'Who pays for the inspection?', a: 'You pay the station directly. The DriveMe fee covers only collection, driving, handover and return.' },
        { q: 'What needs to be in the car?', a: 'Enough fuel or charge, correct seasonal tyres and any wheel-lock key. Please take valuables out before collection.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'workshop',
    category: 'concierge',
    launch: 'priority',
    appointment: 'required',
    icon: 'workshop',
    price: { key: 'serviceRun' },
    related: ['inspection', 'tyre', 'glass'],
    devNote: 'The booking form offers one-way delivery, one-way collection, same-day return, and return on a later date. The driver must never authorise additional work.',
    fi: {
      slug: 'auton-vienti-huoltoon',
      nav: 'Auton nouto huoltoon',
      short: 'Huolto',
      title: 'Auton nouto huoltoon ja palautus | DriveMe',
      description: 'Pidä huoltoaikasi menettämättä työpäivää. DriveMe toimittaa autosi valitsemaasi huoltoon ja palauttaa sen sovitusti.',
      h1: 'Auton nouto huoltoon ja palautus ilman oman aikasi menettämistä',
      lead: 'Pidä huoltoaikasi ja pidä päiväsi. DriveMe hoitaa auton luovutukset, sinä asioit suoraan valitsemasi korjaamon kanssa.',
      keywords: ['auton nouto huoltoon', 'auton vienti huoltoon', 'huollon nouto ja palautus'],
      steps: [
        'Varaat huoltoajan ja sovit työn sisällön korjaamon kanssa.',
        'Noudamme auton kotoa tai työpaikalta ja dokumentoimme kunnon.',
        'Toimitamme auton nimetylle korjaamolle ja kirjaamme vastaanottajan tai avainlaatikkoluovutuksen.',
        'Kun korjaamo ilmoittaa auton valmiiksi, noudamme sen ja palautamme sovittuun osoitteeseen.',
      ],
      included: [
        'Nouto kotoa tai työpaikalta',
        'Toimitus nimetylle korjaamolle',
        'Vastaanottavan henkilön tai avainlaatikkoluovutuksen kirjaaminen',
        'Nouto sen jälkeen, kun korjaamo vahvistaa auton valmiiksi',
        'Palautus sovittuun osoitteeseen',
      ],
      customer: [
        'Varaa huoltoaika ja sovi työmääräys',
        'Anna varausnumero ja korjaamon yhteystiedot',
        'Hyväksy kaikki korjaukset, muutokset ja kustannukset suoraan korjaamon kanssa',
        'Maksa korjaamolle suoraan',
      ],
      excluded: [
        'Auton korjaaminen tai vianmääritys',
        'Korjaamon valitseminen, ellei siitä ole erikseen sovittu',
        'Lisätöiden hyväksyminen',
        'Korjaamon aikataulun tai työn laadun takaaminen',
      ],
      boundary: 'Asiakas varaa huoltoajan, hyväksyy työt ja maksaa korjaamolle suoraan. DriveMe vastaa sovitusta nouto-, ajo-, toimitus- ja luovutuspalvelusta, ei korjaamon työn sisällöstä tai lopputuloksesta.',
      faq: [
        { q: 'Voiko kuljettaja hyväksyä lisätöitä?', a: 'Ei. Kuljettaja ilmoittaa korjaamolle toimittavansa auton asiakkaan puolesta eikä hänellä ole valtuutta hyväksyä töitä. Korjaamo ottaa kaikissa hyväksynnöissä yhteyden suoraan sinuun.' },
        { q: 'Voinko tilata vain toisen suunnan?', a: 'Kyllä. Voit valita pelkän toimituksen, pelkän noudon, saman päivän palautuksen tai palautuksen myöhempänä päivänä.' },
        { q: 'Entä jos huolto kestää odotettua pidempään?', a: 'Sinä päätät: siirrämme palautuksen myöhemmäksi, odotamme veloitettavan odotuksen mukaan tai sovimme uuden ajan. Emme veloita korjaamon ajasta, jos kuljettaja on lähtenyt pois.' },
        { q: 'Miten avaimet luovutetaan, jos korjaamo on kiinni?', a: 'Käytämme korjaamon hyväksymää avainlaatikkoa tai nimettyä vastaanottajaa. Kirjaamme aina ajan, paikan ja tavan.' },
      ],
    },
    en: {
      slug: 'car-to-workshop',
      nav: 'Workshop run',
      short: 'Workshop',
      title: 'Workshop and maintenance run | Pickup and return | DriveMe',
      description: 'Keep your service appointment without losing a working day. DriveMe delivers your car to your chosen workshop and returns it as agreed.',
      h1: 'Workshop pickup and return without losing your day',
      lead: 'Keep your appointment and keep your day. DriveMe handles the vehicle handovers while you deal directly with your chosen workshop.',
      keywords: ['workshop pickup and return', 'car service collection Helsinki'],
      steps: [
        'You book the appointment and agree the work order with the workshop.',
        'We collect the car from home or work and document its condition.',
        'We deliver it to the named workshop and record the receiver or key-drop handover.',
        'When the workshop confirms the car is ready, we collect it and return it to the agreed address.',
      ],
      included: [
        'Pickup from home or work',
        'Delivery to the named workshop',
        'Recording the receiving person’s or key-drop handover',
        'Collection after the workshop confirms readiness',
        'Return to the agreed address',
      ],
      customer: [
        'Book the workshop appointment and agree the work order',
        'Provide the booking reference and workshop contact',
        'Approve all repairs, changes and costs directly with the workshop',
        'Pay the workshop directly',
      ],
      excluded: [
        'Repairing or diagnosing the vehicle',
        'Selecting the workshop unless separately agreed in the future',
        'Approving extra work',
        'Guaranteeing the workshop’s schedule or workmanship',
      ],
      boundary: 'The customer books the appointment, approves the work and pays the workshop directly. DriveMe is responsible for the agreed collection, driving, delivery and handover service.',
      faq: [
        { q: 'Can the driver approve repairs?', a: 'No. The driver states that they are delivering on the customer’s behalf and has no authority to approve work. The workshop contacts you directly for every approval.' },
        { q: 'Can I order only one direction?', a: 'Yes. Choose delivery only, collection only, same-day return, or return on a later date.' },
        { q: 'What if the service takes longer than expected?', a: 'You decide: we move the return to later, wait under the chargeable waiting rule, or reschedule. Workshop time is not billed when the driver has left.' },
        { q: 'How are keys handed over if the workshop is closed?', a: 'We use the workshop’s approved key drop or a named receiver, and always record the time, place and method.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'tyre',
    category: 'concierge',
    launch: 'priority',
    appointment: 'recommended',
    icon: 'tyre',
    price: { key: 'serviceRun' },
    related: ['workshop', 'inspection', 'wash'],
    devNote: 'A walk-in job may be accepted only when the chosen provider confirms walk-ins and the customer accepts possible waiting charges. During peak season, a booked slot should be required.',
    fi: {
      slug: 'auton-vienti-renkaanvaihtoon',
      nav: 'Auton vienti renkaanvaihtoon',
      short: 'Renkaanvaihto',
      title: 'Auton vienti renkaanvaihtoon | DriveMe',
      description: 'Auton nouto renkaanvaihtoon tai rengashotelliin ja palautus sovitusti. Palveluntarjoajan kulut maksetaan erikseen.',
      h1: 'Auton vienti renkaanvaihtoon ilman jonottamista',
      lead: 'Viemme autosi renkaanvaihtoon, rengashotelliin tai suuntaukseen ja palautamme sen kauteen valmiina.',
      keywords: ['auton vienti renkaanvaihtoon', 'renkaanvaihto noutopalvelu', 'rengashotelli nouto'],
      steps: [
        'Varmistat rengasliikkeen ajan tai sen, että liike ottaa auton vastaan ilman ajanvarausta.',
        'Kerrot, missä renkaat ovat: liikkeessä, autossa vai toisessa osoitteessa.',
        'Noudamme auton, dokumentoimme kunnon ja toimitamme sen rengasliikkeeseen.',
        'Palautamme auton sovittuun osoitteeseen, kun liike vapauttaa sen.',
      ],
      included: [
        'Nouto ja palautus',
        'Toimitus nimettyyn rengasliikkeeseen',
        'Luovutuksen tila ja valmistumiskuittaus',
        'Kohtuullinen odotus vain silloin, kun se sisältyy valittuun tuotteeseen',
      ],
      customer: [
        'Varmista, että palveluntarjoaja ottaa auton vastaan pyydettynä aikana',
        'Kerro, ovatko renkaat liikkeessä, autossa vai toisessa nouto-osoitteessa',
        'Maksa rengasliikkeelle suoraan',
        'Ilmoita lukkopulttiavaimen sijainti',
      ],
      excluded: [
        'Renkaat, asennus, säilytys tai suuntausmaksut',
        'Irtorenkaiden kuljetus, ellei siitä ole erikseen sovittu',
        'Rengasturvallisuuden arviointi',
        'Jonotusaika yli sisältyvän odotusajan',
      ],
      boundary: 'Asiakas valitsee rengasliikkeen ja maksaa sille suoraan. DriveMe vastaa auton noudosta, ajosta, luovutuksesta ja palautuksesta.',
      faq: [
        { q: 'Voiko auton viedä renkaanvaihtoon ilman ajanvarausta?', a: 'Vain jos valitsemasi liike ottaa vastaan ilman ajanvarausta ja hyväksyt mahdollisen odotusveloituksen. Sesonkiaikaan edellytämme varattua aikaa, koska jonot ovat pitkiä eikä autolle voi luvata palautusaikaa.' },
        { q: 'Kuljetatteko irtorenkaat?', a: 'Vain erikseen sovittaessa. Kerro varauksessa, ovatko renkaat autossa, liikkeessä vai toisessa osoitteessa, niin sovimme oikean tavan.' },
        { q: 'Arvioitteko renkaideni kunnon?', a: 'Emme. Emme ole rengasliike emmekä arvioi rengasturvallisuutta - se kuuluu valitsemallesi palveluntarjoajalle.' },
        { q: 'Kuka maksaa renkaanvaihdon?', a: 'Sinä maksat rengasliikkeelle suoraan. DriveMe-palkkio kattaa vain auton siirrot.' },
      ],
    },
    en: {
      slug: 'car-to-tyre-service',
      nav: 'Tyre service run',
      short: 'Tyres',
      title: 'Tyre service run | Pickup and return | DriveMe',
      description: 'Collection to a tyre change, tyre hotel or wheel alignment and return as agreed. Provider charges are paid separately.',
      h1: 'Tyre change without the queue',
      lead: 'We take your car to its tyre change, tyre hotel or wheel-alignment visit and return it ready for the season.',
      keywords: ['tyre change pickup service', 'tyre hotel collection Helsinki'],
      steps: [
        'You confirm the slot, or that the provider accepts the car without an appointment.',
        'You tell us where the tyres are: at the provider, in the car, or at another address.',
        'We collect the car, document its condition and deliver it to the tyre provider.',
        'We return the car to the agreed address once the provider releases it.',
      ],
      included: [
        'Pickup and return',
        'Delivery to the named tyre provider',
        'Handover status and completion record',
        'Reasonable waiting only when included in the selected product',
      ],
      customer: [
        'Confirm that the provider accepts the vehicle at the requested time',
        'State whether tyres are at the provider, in the vehicle or at another collection address',
        'Pay the tyre provider directly',
        'Disclose wheel-lock key location',
      ],
      excluded: [
        'Tyres, fitting, storage or alignment charges',
        'Transporting loose tyres unless explicitly accepted',
        'Assessing tyre safety',
        'Queue time beyond the included allowance',
      ],
      boundary: 'The customer chooses the tyre provider and pays it directly. DriveMe is responsible for collection, driving, handover and return.',
      faq: [
        { q: 'Can you take the car without a booked slot?', a: 'Only if your chosen provider accepts walk-ins and you accept a possible waiting charge. In peak season we require a booked slot, because queues make a return time impossible to promise.' },
        { q: 'Do you carry loose tyres?', a: 'Only when separately agreed. Tell us in the booking whether the tyres are in the car, at the provider or at another address.' },
        { q: 'Do you assess my tyres?', a: 'No. We are not a tyre shop and do not judge tyre safety - that is for the provider you choose.' },
        { q: 'Who pays for the tyre work?', a: 'You pay the provider directly. The DriveMe fee covers the vehicle movements only.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'wash',
    category: 'concierge',
    launch: 'priority',
    appointment: 'recommended',
    icon: 'wash',
    price: { key: 'serviceRun' },
    related: ['workshop', 'tyre', 'pickupReturn'],
    devNote: 'For non-appointment washes, require customer prepayment, a provider payment link or confirmed remote payment. The driver should not advance third-party costs.',
    fi: {
      slug: 'auton-vienti-pesuun',
      nav: 'Auton vienti pesuun',
      short: 'Pesu ja detailing',
      title: 'Auton nouto pesuun tai detailingiin | DriveMe',
      description: 'DriveMe vie autosi valitsemaasi autopesuun tai detailing-palveluun ja palauttaa sen. Selkeä DriveMe-hinta etukäteen.',
      h1: 'Auton vienti pesuun tai detailingiin työpäivän aikana',
      lead: 'Autosi pääsee ajanvaraukseensa ilman että se valtaa kalenterisi.',
      keywords: ['auton nouto pesuun', 'autopesu noutopalvelu', 'detailing noutopalvelu'],
      steps: [
        'Valitset pesulan tai detailing-palvelun ja pesupaketin sekä maksat sen palveluntarjoajalle.',
        'Noudamme auton ja dokumentoimme sen kunnon ennen luovutusta.',
        'Toimitamme auton pesuun ja kirjaamme luovutuksen.',
        'Palautamme auton, kun palveluntarjoaja vapauttaa sen.',
      ],
      included: [
        'Nouto, dokumentoitu kunto ja toimitus',
        'Palautus, kun palveluntarjoaja vapauttaa auton',
        'Valinnainen tankkaus tai lataus, jos siitä on erikseen sovittu ja se on ennakkoon maksettu',
      ],
      customer: [
        'Valitse palveluntarjoaja, joka ottaa vastaan varauksen tai ilman ajanvarausta tulevan auton',
        'Valitse ja maksa pesu- tai detailing-paketti',
        'Poista arvoesineet ja kerro herkistä pinnoista tai muutoksista',
      ],
      excluded: [
        'Pesun tai detailingin hinta',
        'Palveluntarjoajan työn laadunvalvonta',
        'Vahinko, jonka on aiheuttanut yksin kolmannen osapuolen palveluntarjoaja',
        'Odotus yli tuotteeseen sisältyvän ajan',
      ],
      boundary: 'Asiakas valitsee pesun ja maksaa sen suoraan palveluntarjoajalle. DriveMe vastaa auton noudosta, ajosta, luovutuksesta ja palautuksesta, ei pesun lopputuloksesta.',
      faq: [
        { q: 'Maksaako kuljettaja pesun puolestani?', a: 'Ei. Kuljettaja ei maksa kolmannen osapuolen kuluja. Maksa pesu etukäteen, käytä palveluntarjoajan maksulinkkiä tai sovi etämaksu suoraan pesulan kanssa.' },
        { q: 'Vastaatteko pesujäljestä?', a: 'Emme valvo palveluntarjoajan työn laatua. Dokumentoimme auton kunnon noudossa ja palautuksessa, joten kummankin ajankohdan kunto on todennettavissa.' },
        { q: 'Entä jos autossani on erikoispinnoite tai teippaus?', a: 'Kerro siitä varauksessa ja valitse palveluntarjoaja, joka osaa käsitellä sen. Välitämme tiedon, mutta emme tee pintaan liittyviä päätöksiä puolestasi.' },
      ],
    },
    en: {
      slug: 'car-to-wash',
      nav: 'Wash and detailing run',
      short: 'Wash',
      title: 'Wash and detailing run | Pickup and return | DriveMe',
      description: 'DriveMe takes your car to your chosen wash or detailing provider and returns it. A clear DriveMe price in advance.',
      h1: 'Wash and detailing during your working day',
      lead: 'Your car gets its appointment without taking over your calendar.',
      keywords: ['car wash pickup service', 'detailing collection Helsinki'],
      steps: [
        'You choose the provider and package and pay the provider for it.',
        'We collect the car and document its condition before handover.',
        'We deliver it to the wash and record the handover.',
        'We return the car once the provider releases it.',
      ],
      included: [
        'Collection, documented condition and delivery',
        'Return after the provider releases the car',
        'Optional refuelling or EV charging if separately ordered and prepaid',
      ],
      customer: [
        'Choose a provider that accepts the booking or walk-in',
        'Select and pay for the wash/detailing package',
        'Remove valuables and disclose sensitive finishes or modifications',
      ],
      excluded: [
        'The wash or detailing price',
        'Quality control of the provider’s workmanship',
        'Damage caused solely by the third-party provider',
        'Waiting beyond the product allowance',
      ],
      boundary: 'The customer chooses and pays the wash provider directly. DriveMe is responsible for collection, driving, handover and return, not for the result of the wash.',
      faq: [
        { q: 'Will the driver pay for the wash?', a: 'No. Drivers do not advance third-party costs. Prepay, use the provider’s payment link, or arrange remote payment with the provider.' },
        { q: 'Are you responsible for the wash quality?', a: 'We do not quality-control the provider’s work. We document the car at collection and at return, so the condition at both points is evidenced.' },
        { q: 'My car has a coating or wrap - is that a problem?', a: 'Tell us in the booking and choose a provider equipped for it. We pass the information on but do not make finish-related decisions for you.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'glass',
    category: 'concierge',
    launch: 'priority',
    appointment: 'required',
    icon: 'glass',
    price: { key: 'serviceRun' },
    related: ['workshop', 'inspection', 'relocation'],
    devNote: 'Do not accept a visibly unsafe, leaking, collision-damaged or warning-critical vehicle for driven transfer. Route such work to a towing partner.',
    fi: {
      slug: 'auton-vienti-korjaukseen',
      nav: 'Lasi, kolari ja takaisinkutsu',
      short: 'Korjaus',
      title: 'Auton vienti korjaukseen, lasiin tai takaisinkutsuun | DriveMe',
      description: 'Tuulilasista takaisinkutsuun: DriveMe hoitaa ajokuntoisen auton siirron ja luovutuksen erikoisliikkeeseen.',
      h1: 'Auton vienti korjaukseen, lasiin tai takaisinkutsuun',
      lead: 'Tuulilasin ajanvarauksesta valmistajan takaisinkutsuun - DriveMe hoitaa ajokuntoisen auton siirron ja luovutuksen.',
      keywords: ['auton vienti korjaukseen', 'tuulilasi noutopalvelu', 'takaisinkutsu auton siirto'],
      steps: [
        'Varaat ajan lasiliikkeeseen, korikorjaamoon tai merkkiliikkeeseen ja asioit vakuutusyhtiön kanssa itse.',
        'Annat meille varaus- tai vahinkonumeron ja kohteen yhteystiedot.',
        'Noudamme auton, dokumentoimme kunnon ja luovutamme sen kohteessa.',
        'Palautamme auton, kun palveluntarjoaja vapauttaa sen.',
      ],
      included: [
        'Toimitus ja/tai nouto',
        'Luovutus varausnumerolla',
        'Kunnon dokumentointi',
        'Palautus, kun palveluntarjoaja vapauttaa auton',
      ],
      customer: [
        'Varmista, että ajanvaraus on vahvistettu',
        'Asioi suoraan vakuutusyhtiön ja korjaajan kanssa',
        'Anna vahinko- tai varausnumero',
        'Hyväksy kaikki kustannukset ja työt',
      ],
      excluded: [
        'Vakuutuskorvausasiointi',
        'Vahingon arviointi',
        'Kolarissa vaurioituneen tai turvattoman auton hinaus',
        'Korjausneuvonta tai takuupäätökset',
      ],
      boundary: 'Asiakas asioi vakuutusyhtiön ja korjaajan kanssa ja hyväksyy työt. DriveMe vastaa ajokuntoisen auton siirrosta ja luovutuksesta.',
      faq: [
        { q: 'Voitteko siirtää kolaroidun auton?', a: 'Emme, jos auto ei ole turvallisesti ajettavissa. Emme ota ajettavaksi näkyvästi turvatonta, vuotavaa, kolarivaurioitunutta tai kriittisen varoituksen näyttävää autoa - ohjaamme työn hinauskumppanille.' },
        { q: 'Hoidatteko vakuutusasiat?', a: 'Emme. Vakuutuskorvaus, vahingon arviointi ja korjauspäätökset ovat sinun ja vakuutusyhtiösi välisiä. Me hoidamme siirron ja luovutuksen.' },
        { q: 'Tarvitaanko vahvistettu ajanvaraus?', a: 'Kyllä. Lasi-, kori- ja takaisinkutsutöissä edellytämme vahvistettua aikaa.' },
      ],
    },
    en: {
      slug: 'car-to-body-shop',
      nav: 'Glass, body shop and recall',
      short: 'Specialist',
      title: 'Glass, body shop and recall run | DriveMe',
      description: 'From a windscreen appointment to a manufacturer recall, DriveMe handles the roadworthy vehicle movement and handover.',
      h1: 'Glass, body shop, recall and specialist runs',
      lead: 'From a windscreen appointment to a manufacturer recall, DriveMe handles the roadworthy vehicle movement and handover.',
      keywords: ['windscreen appointment car collection', 'recall vehicle transfer Helsinki'],
      steps: [
        'You book the glass, body shop or dealer appointment and deal with your insurer yourself.',
        'You give us the booking or claim reference and the destination contact.',
        'We collect the car, document its condition and hand it over at the destination.',
        'We return the car once the provider releases it.',
      ],
      included: [
        'Delivery and/or collection',
        'Booking-reference handover',
        'Condition documentation',
        'Return when released by the provider',
      ],
      customer: [
        'Have a confirmed appointment',
        'Deal directly with insurer and repairer',
        'Provide claim or booking reference',
        'Approve all costs and work',
      ],
      excluded: [
        'Insurance claim administration',
        'Damage assessment',
        'Towing accident-damaged or unsafe vehicles',
        'Repair advice or warranty decisions',
      ],
      boundary: 'The customer deals with the insurer and repairer and approves the work. DriveMe moves and hands over a roadworthy vehicle.',
      faq: [
        { q: 'Can you move a collision-damaged car?', a: 'Not if it cannot be driven safely. We do not accept a visibly unsafe, leaking, collision-damaged or warning-critical vehicle for a driven transfer - we route it to a towing partner.' },
        { q: 'Do you handle the insurance claim?', a: 'No. The claim, damage assessment and repair decisions are between you and your insurer. We handle the movement and handover.' },
        { q: 'Is a confirmed appointment required?', a: 'Yes, for glass, body shop and recall work.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'pickupReturn',
    category: 'concierge',
    launch: 'priority',
    appointment: 'depends',
    icon: 'pickup',
    price: { key: 'pickupReturn' },
    related: ['inspection', 'workshop', 'relocation'],
    devNote: 'This is the general-intent landing page for pickup/return searches. It funnels into the specific service pages rather than duplicating them.',
    fi: {
      slug: 'auton-nouto-ja-palautus',
      nav: 'Auton nouto ja palautus',
      short: 'Nouto ja palautus',
      title: 'Auton noutopalvelu | Nouto ja palautus | DriveMe',
      description: 'Auton nouto ja palautus valitsemaasi palveluun tai osoitteeseen pääkaupunkiseudulla. Dokumentoitu luovutus ja etukäteen vahvistettu hinta.',
      h1: 'Auton nouto- ja palautuspalvelu',
      lead: 'Yksi luotettava kumppani auton siirtoihin: noudamme ajokuntoisen autosi, viemme sen valitsemaasi palveluun tai osoitteeseen ja palautamme sen sovitusti.',
      keywords: ['auton noutopalvelu', 'auton nouto ja palautus', 'auton hakupalvelu'],
      steps: [
        'Valitset palvelun ja kerrot nouto-osoitteen, kohteen ja ajankohdan.',
        'Vahvistamme kuljettajan, ajan ja kiinteän DriveMe-hinnan.',
        'Noudamme auton dokumentoidusti ja pidämme sinut ajan tasalla.',
        'Palautamme tai luovutamme auton sovitusti ja kuittaamme työn valmiiksi.',
      ],
      included: [
        'Sovittu noutoaikaikkuna kotoa tai työpaikalta',
        'Kunnon, mittarilukeman ja polttoaine- tai lataustason dokumentointi',
        'Ajo asiakkaan valitsemaan kohteeseen',
        'Luovutuksen kirjaaminen ja palautus sovittuun osoitteeseen',
      ],
      customer: [
        'Varaa tarvittava ajanvaraus palveluntarjoajalta',
        'Anna kohteen tiedot, yhteyshenkilö ja mahdollinen varausnumero',
        'Varmista auton kelpoisuus ja avainten luovutus',
        'Maksa kolmannen osapuolen palvelut suoraan',
      ],
      excluded: [
        'Kolmannen osapuolen työ ja sen maksut',
        'Ajokiellossa olevan tai turvattoman auton siirto',
        'Hinaus tai lavettikuljetus',
        'Auton säilytys',
      ],
      boundary: 'DriveMe vastaa noudosta, ajosta, toimituksesta ja luovutuksesta. Kolmannen osapuolen palvelu on aina asiakkaan ja palveluntarjoajan välinen sopimus.',
      faq: [
        { q: 'Mihin palveluihin voitte viedä auton?', a: 'Katsastukseen, huoltoon, renkaanvaihtoon, pesuun, lasi- ja korikorjaamoon, merkkiliikkeen takaisinkutsuun, autoliikkeeseen tai mihin tahansa sovittuun osoitteeseen pääkaupunkiseudulla. Valitset palveluntarjoajan itse.' },
        { q: 'Voinko käyttää omaa korjaamoani?', a: 'Kyllä, ja se on koko idea. Emme ole sidoksissa yhteen korjaamoon, asemaan tai ketjuun.' },
        { q: 'Miten hinta muodostuu?', a: 'Hinta perustuu palveluun, osoitteisiin, ajankohtaan ja odotukseen. Näet ohjeellisen hinnan heti ja vahvistamme kiinteän hinnan ennen ajoa. Kolmannen osapuolen maksut eivät sisälly.' },
        { q: 'Pitääkö minun olla paikalla noudossa?', a: 'Ei, jos avainten luovutus on sovittu varauksessa ja luovuttaja on valtuutettu. Kirjaamme aina, kuka luovutti avaimet ja milloin.' },
      ],
    },
    en: {
      slug: 'vehicle-pickup-and-return',
      nav: 'Pickup and return',
      short: 'Pickup and return',
      title: 'Vehicle pickup and return service | DriveMe',
      description: 'Collection and return of your car to any provider or address in the Helsinki capital region, with documented handovers and a price confirmed in advance.',
      h1: 'Vehicle pickup and return service',
      lead: 'One trusted partner for vehicle movements: we collect your roadworthy car, take it to the provider or address you choose and return it as agreed.',
      keywords: ['vehicle pickup service Helsinki', 'car collection and delivery'],
      steps: [
        'You choose the service and give us the collection address, destination and timing.',
        'We confirm the driver, the time and a fixed DriveMe price.',
        'We collect the car with documentation and keep you updated.',
        'We return or hand over the car as agreed and record completion.',
      ],
      included: [
        'Agreed collection window from home or work',
        'Condition, mileage and fuel or charge documentation',
        'Driving to the destination the customer chooses',
        'Handover record and return to the agreed address',
      ],
      customer: [
        'Book any appointment the provider requires',
        'Give the destination details, contact and booking reference',
        'Ensure vehicle eligibility and key handover',
        'Pay third-party services directly',
      ],
      excluded: [
        'Third-party work and its charges',
        'Moving a driving-banned or unsafe vehicle',
        'Towing or trailer transport',
        'Vehicle storage',
      ],
      boundary: 'DriveMe is responsible for collection, driving, delivery and handover. The third-party service is always an agreement between the customer and the provider.',
      faq: [
        { q: 'Where can you take my car?', a: 'Inspection, workshop, tyre service, wash, glass and body shops, dealer recalls, dealerships, or any agreed address in the capital region. You choose the provider.' },
        { q: 'Can I use my own workshop?', a: 'Yes - that is the whole point. We are not tied to one workshop, station or chain.' },
        { q: 'How is the price formed?', a: 'From the service, the addresses, the timing and expected waiting. You see an indicative price immediately and we confirm a fixed price before the drive. Third-party charges are not included.' },
        { q: 'Do I need to be there at collection?', a: 'Not if the key handover is agreed in the booking and the person handing over is authorised. We always record who handed the keys over and when.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'relocation',
    category: 'concierge',
    launch: 'priority',
    appointment: 'none',
    icon: 'relocation',
    price: { key: 'oneWay' },
    related: ['dealer', 'pickupReturn', 'business'],
    devNote: 'Start with scheduled capital-region and domestic transfers. Price long-distance jobs individually until route and driver-return economics are proven.',
    fi: {
      slug: 'auton-siirtopalvelu',
      nav: 'Auton siirtopalvelu',
      short: 'Siirto',
      title: 'Auton siirtopalvelu | Helsinki, Espoo ja Vantaa | DriveMe',
      description: 'Luotettava ajokuntoisen auton siirtopalvelu osoitteesta toiseen dokumentoidulla noudolla ja luovutuksella.',
      h1: 'Auton siirtopalvelu osoitteesta toiseen',
      lead: 'Siirrämme ajokuntoisen autosi sovitusta osoitteesta toiseen, dokumentoidulla luovutuksella molemmissa päissä.',
      keywords: ['auton siirtopalvelu', 'ajoneuvon siirto', 'auton kuljetus kuljettamalla'],
      steps: [
        'Kerrot nouto- ja toimitusosoitteen sekä yhteyshenkilöt molemmissa päissä.',
        'Vahvistamme kiinteän hinnan reitin, ajankohdan ja kuljettajan paluulogistiikan perusteella.',
        'Noudamme auton, dokumentoimme kunnon, mittarilukeman ja polttoaine- tai lataustason.',
        'Toimitamme auton ja kuittaamme luovutuksen valtuutetulle vastaanottajalle.',
      ],
      included: [
        'Yhdensuuntainen ajettu siirto',
        'Nouto- ja toimituskuvat',
        'Mittarilukema-, polttoaine- tai lataustaso- ja avainluovutuskirjaukset',
        'Tilailmoitukset',
      ],
      customer: [
        'Nimeä valtuutetut yhteyshenkilöt molempiin päihin',
        'Varmista voimassa oleva rekisteröinti, vakuutus, renkaat ja ajokunto',
        'Ilmoita viat, muutokset ja erityiset hallintalaitteet',
        'Maksa polttoaine, lataus, tiemaksut ja pysäköinti tarjouksen mukaisesti',
      ],
      excluded: [
        'Kuljetus lavetilla tai perävaunulla',
        'Liikennekäytöstä poistetun tai ajokiellossa olevan auton siirto',
        'Kansainväliset siirrot, ellei niistä ole erikseen tarjottu',
        'Säilytys',
      ],
      boundary: 'DriveMe vastaa ajetusta siirrosta ja dokumentoidusta luovutuksesta. Auton kelpoisuudesta ja tiedoista vastaa asiakas.',
      faq: [
        { q: 'Ajetaanko auto vai kuljetetaanko se lavetilla?', a: 'Ajamme auton. Se on nopeampaa ja edullisempaa ajokuntoiselle autolle. Jos auto ei ole ajokuntoinen tai sitä ei saa ajaa, tarvitaan lavetti - silloin ohjaamme sinut kuljetuskumppanille.' },
        { q: 'Siirrättekö autoja pääkaupunkiseudun ulkopuolelle?', a: 'Kyllä, mutta hinnoittelemme pitkät siirrot tapauskohtaisesti, koska kuljettajan paluumatka on osa kustannusta. Pyydä tarjous reitille.' },
        { q: 'Kuka maksaa polttoaineen ja tiemaksut?', a: 'Ne kerrotaan tarjouksessa erikseen. Emme piilota niitä hintaan.' },
        { q: 'Voiko auton vastaanottaa joku muu?', a: 'Kyllä. Nimeä valtuutettu vastaanottaja varauksessa, niin kirjaamme luovutuksen hänelle.' },
      ],
    },
    en: {
      slug: 'vehicle-relocation',
      nav: 'Vehicle relocation',
      short: 'Relocation',
      title: 'Vehicle relocation | Helsinki, Espoo and Vantaa | DriveMe',
      description: 'Reliable driven relocation of a roadworthy car from one address to another, with documented collection and handover.',
      h1: 'Vehicle relocation between addresses',
      lead: 'We move your roadworthy vehicle from one agreed address to another, with a documented handover at both ends.',
      keywords: ['vehicle relocation Helsinki', 'driven car transfer Finland'],
      steps: [
        'You give the collection and delivery addresses and the contacts at both ends.',
        'We confirm a fixed price from the route, the timing and the driver’s return logistics.',
        'We collect the car and document condition, mileage and fuel or charge level.',
        'We deliver the car and record the handover to the authorised recipient.',
      ],
      included: [
        'One-way driven relocation',
        'Pickup and delivery photos',
        'Mileage, fuel/charge and key handover records',
        'Status notifications',
      ],
      customer: [
        'Provide authorised contacts at both ends',
        'Ensure valid registration, insurance, tyres and roadworthiness',
        'Declare faults, modifications and special controls',
        'Pay fuel, charging, tolls and parking as stated in the quote',
      ],
      excluded: [
        'Transport by truck or trailer',
        'Moving deregistered or driving-banned vehicles',
        'International movement unless expressly quoted',
        'Storage',
      ],
      boundary: 'DriveMe is responsible for the driven move and the documented handover. Vehicle eligibility and disclosure are the customer’s responsibility.',
      faq: [
        { q: 'Is the car driven or trailered?', a: 'We drive it. That is faster and cheaper for a roadworthy car. If the car cannot legally or safely be driven, it needs a trailer and we point you to a transport partner.' },
        { q: 'Do you move cars outside the capital region?', a: 'Yes, but long-distance moves are priced individually because the driver’s return trip is part of the cost. Ask for a quote on the route.' },
        { q: 'Who pays fuel and tolls?', a: 'They are stated separately in the quote. We do not hide them in the price.' },
        { q: 'Can someone else receive the car?', a: 'Yes. Name an authorised recipient in the booking and we record the handover to them.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'dealer',
    category: 'concierge',
    launch: 'priority',
    appointment: 'required',
    icon: 'dealer',
    price: { key: 'oneWay' },
    related: ['relocation', 'pickupReturn', 'business'],
    devNote: 'Use a limited written authorisation that permits physical handover only. Do not allow drivers to sign financial or liability admissions.',
    fi: {
      slug: 'auton-palautus-autoliikkeeseen',
      nav: 'Palautus autoliikkeeseen',
      short: 'Autoliike ja leasing',
      title: 'Auton palautus leasingyhtiölle tai autoliikkeeseen | DriveMe',
      description: 'DriveMe hoitaa ajokuntoisen auton dokumentoidun toimituksen autoliikkeeseen, leasingyhtiölle tai vuokraamoon.',
      h1: 'Auton nouto tai palautus autoliikkeeseen ja leasingyhtiölle',
      lead: 'DriveMe hoitaa fyysisen luovutuksen; kauppa-, leasing- tai vuokrasopimus pysyy sinun ja palveluntarjoajan välisenä.',
      keywords: ['auton palautus leasingyhtiölle', 'auton nouto autoliikkeestä', 'vuokra-auton palautus'],
      steps: [
        'Varmistat, että vastaanottaja hyväksyy valtuutetun kolmannen osapuolen luovuttamaan tai noutamaan auton.',
        'Toimitat rajatun kirjallisen valtuutuksen ja tarvittavat tunnistetiedot.',
        'Noudamme auton, dokumentoimme kunnon ja mittarilukeman.',
        'Luovutamme auton nimetylle henkilölle tai hyväksyttyyn avainlaatikkoon ja kuittaamme luovutuksen.',
      ],
      included: [
        'Auton nouto tai palautus',
        'Kunto- ja mittarilukemadokumentointi',
        'Avainten ja asiakirjojen vastaanotto',
        'Luovutus nimetylle henkilölle tai hyväksytysti avainlaatikkoon',
      ],
      customer: [
        'Varmista, että palveluntarjoaja sallii valtuutetun kolmannen osapuolen luovutuksen tai noudon',
        'Toimita vaadittu valtuutus ja tunnistautuminen',
        'Maksa palveluntarjoajan veloitukset suoraan',
        'Tarkista ja hyväksy sopimusasiakirjat henkilökohtaisesti',
      ],
      excluded: [
        'Kauppa-, rahoitus-, leasingin päättämis- tai vahinkosopimuksen allekirjoittaminen asiakkaan puolesta',
        'Auton arvon määrittäminen',
        'Ilmoittamattomien veloitusten hyväksyminen',
        'Takuu siitä, että palveluntarjoaja hyväksyy auton',
      ],
      boundary: 'Kuljettajalla on valtuutus vain fyysiseen luovutukseen. Kuljettaja ei allekirjoita taloudellisia sitoumuksia eikä vastuunmyöntöjä puolestasi.',
      faq: [
        { q: 'Voiko kuljettaja allekirjoittaa palautuspöytäkirjan?', a: 'Kuljettaja voi kuitata fyysisen luovutuksen, mutta ei hyväksy vahinkoarvioita, veloituksia eikä sopimusehtoja. Ne kuuluvat sinulle.' },
        { q: 'Entä jos leasingyhtiö väittää autossa olevan uusia vaurioita?', a: 'Dokumentoimme auton kunnon noudossa ja luovutuksessa aikaleimatuin kuvin, joten sinulla on todiste kunnosta luovutushetkellä. Vahinkoneuvottelu käydään sinun ja yhtiön välillä.' },
        { q: 'Tarvitaanko kirjallinen valtuutus?', a: 'Kyllä. Käytämme rajattua valtuutusta, joka oikeuttaa vain fyysiseen luovutukseen. Lähetämme mallin varauksen vahvistuksen yhteydessä.' },
      ],
    },
    en: {
      slug: 'dealer-and-lease-handover',
      nav: 'Dealer and lease handover',
      short: 'Dealer and lease',
      title: 'Dealer, lease and rental handover | DriveMe',
      description: 'DriveMe handles the documented delivery of a roadworthy car to a dealership, leasing company or rental branch.',
      h1: 'Dealer, lease and rental handover',
      lead: 'DriveMe manages the physical handover; the customer keeps the purchase, lease or rental agreement directly with the provider.',
      keywords: ['lease return service', 'dealership car collection Helsinki'],
      steps: [
        'You confirm that the provider accepts an authorised third party to hand over or collect.',
        'You supply the limited written authorisation and required identification.',
        'We collect the car and document condition and mileage.',
        'We hand it over to the named person or approved key drop and record the handover.',
      ],
      included: [
        'Vehicle pickup or return',
        'Condition and mileage documentation',
        'Receipt of keys/documents',
        'Named-person or approved key-drop handover',
      ],
      customer: [
        'Confirm that the provider permits an authorised third party to hand over or collect',
        'Supply the required authorisation and identification',
        'Settle provider charges directly',
        'Review and approve contractual documents personally',
      ],
      excluded: [
        'Signing a purchase, finance, lease termination or damage agreement for the customer',
        'Valuing the vehicle',
        'Accepting undisclosed charges',
        'Guaranteeing a provider’s acceptance',
      ],
      boundary: 'The driver is authorised for the physical handover only, and signs no financial commitment or admission of liability on your behalf.',
      faq: [
        { q: 'Can the driver sign the return report?', a: 'The driver can acknowledge the physical handover, but does not accept damage assessments, charges or contract terms. Those stay with you.' },
        { q: 'What if the leasing company claims new damage?', a: 'We document the car at collection and at handover with timestamped photos, so you have evidence of its condition at handover. The damage discussion is between you and the company.' },
        { q: 'Is a written authorisation needed?', a: 'Yes. We use a limited authorisation covering physical handover only, and send a template with your booking confirmation.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'personalDriver',
    category: 'driver',
    launch: 'gated',
    appointment: 'none',
    icon: 'driver',
    price: { key: 'personalDriver' },
    related: ['safeRideHome', 'airport', 'business'],
    devNote: 'Retain as a premium category, but keep alcohol-heavy positioning off the homepage. Lead with time, convenience, events, business and airport use. Regulatory and insurance clearance is required (Gate A).',
    fi: {
      slug: 'oma-kuljettaja',
      nav: 'Oma kuljettaja',
      short: 'Oma kuljettaja',
      title: 'Oma kuljettaja omalle autollesi | Kuskipalvelu | DriveMe',
      description: 'Ammattikuljettaja ajaa omaa autoasi illan, tapahtuman, työpäivän tai usean pysähdyksen ajan pääkaupunkiseudulla.',
      h1: 'Oma kuljettaja asiakkaan omalle autolle',
      lead: 'Sinun autosi, sinun suunnitelmasi, ammattikuljettaja - illaksi, tapahtumaan tai usean pysähdyksen päiväksi.',
      keywords: ['oma kuljettaja', 'henkilökohtainen kuljettaja', 'kuskipalvelu omalla autolla'],
      steps: [
        'Kerrot aikataulun, nouto-osoitteen, pysähdykset ja kohteen.',
        'Vahvistamme kuljettajan ja hinnan ennen ajoa.',
        'Kuljettaja saapuu sovittuun aikaan ja ajaa omaa autoasi.',
        'Auto ja avaimet luovutetaan sinulle sovitussa paikassa.',
      ],
      included: [
        'Kuljettajan aika vahvistetun aikataulun mukaan',
        'Sovittu nouto, pysähdykset ja määränpää',
        'Dokumentoitu kuljettajan henkilöllisyys ja tukiyhteystieto',
        'Auton ja avainten turvallinen luovutus',
      ],
      customer: [
        'Ole kykenevä nousemaan autoon ja matkustamaan turvallisesti matkustajana',
        'Anna käyttöön laillinen, vakuutettu ja ajokuntoinen auto',
        'Ilmoita erityiset hallintalaitteet',
        'Maksa pysäköinti, tiemaksut ja auton energia, ellei tarjouksessa toisin sanota',
      ],
      excluded: [
        'Ilman saattajaa matkustavan lapsen kuljettaminen',
        'Hoidollinen valvonta tai avustamisvelvoitteet',
        'Turvattoman auton ajaminen',
        'Rajoittamaton odotus tai vahvistamattomat jatkot',
      ],
      boundary: 'Kuljettajapalvelu asiakkaan omalla autolla edellyttää viranomais- ja vakuutusvahvistusta. Emme markkinoi palvelua käytettävissä olevana ennen kuin vahvistukset ovat kirjallisina.',
      faq: [
        { q: 'Ajaako kuljettaja omaa autoani vai teidän autoanne?', a: 'Omaa autoasi. Se on palvelun ydin: tuttu auto, omat lastenistuimet ja tavarat, ei siirtymistä vieraaseen autoon.' },
        { q: 'Onko palvelu jo saatavilla?', a: 'Matkustajakuljetus asiakkaan omalla autolla odottaa viranomais- ja vakuutusvahvistusta. Otamme yhteydenottoja vastaan, mutta emme vahvista ajoja ennen kuin asia on kirjallisesti varmistettu.' },
        { q: 'Onko tunneille minimiä?', a: 'Suositeltu minimi on kaksi tuntia. Kerromme hinnan ja minimin varauksen yhteydessä.' },
        { q: 'Kuljetatteko lapsen yksin?', a: 'Emme. Ilman saattajaa matkustavan lapsen kuljetus on suljettu palvelun ulkopuolelle.' },
      ],
    },
    en: {
      slug: 'personal-driver',
      nav: 'Personal driver',
      short: 'Personal driver',
      title: 'Personal driver for your own car | DriveMe',
      description: 'A professional driver operates your own car for an evening, an event, a business day or a multi-stop schedule in the capital region.',
      h1: 'A personal driver for your own car',
      lead: 'Your vehicle, your plans, a professional driver - for an evening, an event or a multi-stop day.',
      keywords: ['personal driver own car', 'chauffeur for my car Helsinki'],
      steps: [
        'You tell us the schedule, pickup, stops and destination.',
        'We confirm the driver and the price before the drive.',
        'The driver arrives at the agreed time and drives your own car.',
        'The car and keys are handed back to you at the agreed place.',
      ],
      included: [
        'Driver time under the confirmed schedule',
        'Agreed pickup, stops and destination',
        'Documented driver identity and support contact',
        'Safe handover of vehicle and keys',
      ],
      customer: [
        'Be fit to enter and use the vehicle safely as a passenger',
        'Provide a legal, insured and roadworthy vehicle',
        'Disclose special controls',
        'Pay parking, tolls and vehicle energy unless the quote says otherwise',
      ],
      excluded: [
        'Transporting an unaccompanied child',
        'Medical supervision or assisted-care obligations',
        'Driving an unsafe vehicle',
        'Unlimited waiting or unconfirmed extensions',
      ],
      boundary: 'Driver service in the customer’s own car requires regulatory and insurance clearance. We do not market it as available until those confirmations are in writing.',
      faq: [
        { q: 'Does the driver use my car or yours?', a: 'Yours. That is the point of the service: a familiar car, your own child seats and belongings, no transfer into a strange vehicle.' },
        { q: 'Is the service available now?', a: 'Passenger transport in the customer’s own car is awaiting regulatory and insurance confirmation. We take expressions of interest but do not confirm jobs until that is confirmed in writing.' },
        { q: 'Is there an hourly minimum?', a: 'The recommended minimum is two hours. We state the price and minimum with your booking.' },
        { q: 'Do you transport a child alone?', a: 'No. Unaccompanied child transport is excluded from the service.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'safeRideHome',
    category: 'driver',
    launch: 'gated',
    appointment: 'none',
    icon: 'home',
    price: { key: 'designated' },
    related: ['personalDriver', 'airport'],
    devNote: 'Safe ride home is a use case of the personal-driver category, not a separate operation. Keep alcohol-heavy positioning off the homepage.',
    fi: {
      slug: 'turvallinen-kotiinkuljetus',
      nav: 'Turvallinen kotiinkuljetus',
      short: 'Kotiinkuljetus',
      title: 'Kuljettaja sinulle ja autollesi kotiin | DriveMe',
      description: 'Kuljettaja ajaa sinut ja autosi kotiin illan päätteeksi. Auto ei jää kaupungille eikä sitä tarvitse hakea seuraavana aamuna.',
      h1: 'Kuljettaja sinulle ja autollesi kotiin',
      lead: 'Sinä ja autosi pääsette perille yhdellä matkalla - illan, tapahtuman tai pitkän työpäivän jälkeen.',
      keywords: ['turvallinen kotiinkuljetus', 'kuljettaja kotiin omalla autolla'],
      steps: [
        'Kerrot nouto-osoitteen, ajankohdan ja kohteen.',
        'Vahvistamme kuljettajan ja kiinteän hinnan.',
        'Kuljettaja saapuu ja ajaa sinut sekä autosi perille.',
        'Auto ja avaimet jäävät sinulle kotiin.',
      ],
      included: [
        'Kuljettaja sovittuun aikaan',
        'Ajo sinun autollasi sovittuun osoitteeseen',
        'Dokumentoitu kuljettajan henkilöllisyys ja tukiyhteystieto',
        'Auton ja avainten luovutus perillä',
      ],
      customer: [
        'Ole kykenevä nousemaan autoon ja matkustamaan turvallisesti matkustajana',
        'Anna käyttöön laillinen, vakuutettu ja ajokuntoinen auto',
        'Ilmoita erityiset hallintalaitteet',
        'Maksa pysäköinti ja tiemaksut, ellei tarjouksessa toisin sanota',
      ],
      excluded: [
        'Hoidollinen valvonta tai avustaminen',
        'Ilman saattajaa matkustavan lapsen kuljettaminen',
        'Turvattoman auton ajaminen',
        'Rajoittamaton odotus',
      ],
      boundary: 'Palvelu kuuluu kuljettajakategoriaan ja edellyttää samaa viranomais- ja vakuutusvahvistusta kuin muu matkustajakuljetus.',
      faq: [
        { q: 'Miksi tämä on parempi kuin taksi?', a: 'Autosi tulee kotiin kanssasi. Sitä ei tarvitse hakea aamulla, eikä pysäköinnistä kerry maksuja tai sakkoja.' },
        { q: 'Onko palvelu jo saatavilla?', a: 'Ei vielä. Matkustajakuljetus asiakkaan omalla autolla odottaa viranomais- ja vakuutusvahvistusta.' },
        { q: 'Voiko mukana olla useampi matkustaja?', a: 'Kyllä, autosi rekisteröidyn matkustajamäärän ja turvavöiden mukaan.' },
      ],
    },
    en: {
      slug: 'safe-ride-home',
      nav: 'Safe ride home',
      short: 'Safe ride home',
      title: 'A driver for you and your car home | DriveMe',
      description: 'A driver takes you and your own car home at the end of the evening, so the car is not left in town.',
      h1: 'A driver for you and your car home',
      lead: 'You and your car both get home in one journey - after an evening, an event or a long working day.',
      keywords: ['designated driver own car Helsinki', 'safe ride home service'],
      steps: [
        'You give the pickup address, timing and destination.',
        'We confirm the driver and a fixed price.',
        'The driver arrives and drives you and your car home.',
        'The car and keys stay with you at home.',
      ],
      included: [
        'A driver at the agreed time',
        'Driving your own car to the agreed address',
        'Documented driver identity and support contact',
        'Handover of vehicle and keys on arrival',
      ],
      customer: [
        'Be fit to enter and use the vehicle safely as a passenger',
        'Provide a legal, insured and roadworthy vehicle',
        'Disclose special controls',
        'Pay parking and tolls unless the quote says otherwise',
      ],
      excluded: [
        'Medical supervision or assistance',
        'Transporting an unaccompanied child',
        'Driving an unsafe vehicle',
        'Unlimited waiting',
      ],
      boundary: 'This sits in the driver category and needs the same regulatory and insurance clearance as any passenger transport.',
      faq: [
        { q: 'Why is this better than a taxi?', a: 'Your car comes home with you. No morning retrieval, no overnight parking charges or tickets.' },
        { q: 'Is the service available now?', a: 'Not yet. Passenger transport in the customer’s own car is awaiting regulatory and insurance confirmation.' },
        { q: 'Can more than one passenger travel?', a: 'Yes, up to your car’s registered seating and seat belts.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'airport',
    category: 'driver',
    launch: 'gated',
    appointment: 'flight',
    icon: 'airport',
    price: { key: 'airport' },
    related: ['personalDriver', 'relocation', 'safeRideHome'],
    devNote: 'Launch gate, not an automatic launch item. Obtain written confirmation from Traficom and the insurer on paid passenger transport in a customer\'s privately registered car. Do not rely only on the driver\'s taxi licence.',
    fi: {
      slug: 'lentokentta-kuljettajapalvelu',
      nav: 'Kuljettaja lentoasemalle',
      short: 'Lentoasema',
      title: 'Kuljettaja lentoasemalle omalla autolla | DriveMe',
      description: 'Matka lentoasemalle tai sieltä pois omassa autossasi, omilla matkatavaroilla ja lastenistuimilla.',
      h1: 'Kuljettaja lentoasemalle asiakkaan omalla autolla',
      lead: 'Matkusta lentoasemalle tai sieltä pois tutulla autollasi - matkatavarat ja lastenistuimet ovat jo omasi.',
      keywords: ['kuljettaja lentoasemalle', 'lentokenttäkuljetus omalla autolla'],
      steps: [
        'Kerrot lennon tiedot, matkustajamäärän ja matkatavarat.',
        'Sovimme, missä auto ja avaimet ovat lähdön jälkeen tai ennen paluuta.',
        'Vahvistamme kuljettajan, aikataulun ja hinnan.',
        'Kuljettaja ajaa sinut lentoasemalle ja hoitaa auton sovitusti.',
      ],
      included: [
        'Ennalta varattu kuljettaja ja sovittu tukilogistiikka',
        'Lento- ja aikataulutiedot',
        'Asiakkaan ja auton luovutus valitun vaihtoehdon mukaan',
        'Tarjouksessa mainitut lentoaseman jättömaksut',
      ],
      customer: [
        'Anna tarkat lento- ja matkatavaratiedot',
        'Varmista, että auto on sopiva ja laillinen',
        'Sovi, missä auto ja avaimet ovat lähdön jälkeen tai ennen paluuta',
        'Hanki ja asenna lastenistuimet itse',
      ],
      excluded: [
        'Lentoaseman pysäköinti, ellei siitä ole tarjottu',
        'Lentokenttäavustus tai matkatavaroiden käsittely',
        'Auton säilytys',
        'Perinteinen lentokenttäkuljetus DriveMen omalla autolla, kunnes tuote on luvitettu ja käytössä',
      ],
      boundary: 'Palvelu on lupaportti, ei automaattinen lanseeraus. Emme vahvista ajoja ennen kirjallista viranomais- ja vakuutusvahvistusta.',
      faq: [
        { q: 'Mihin autoni jää lennon ajaksi?', a: 'Sovitaan varauksessa. Yleisimmät vaihtoehdot ovat auton palautus kotiisi tai sovittuun osoitteeseen, tai sen nouto paluupäivänä. Säilytys ei sisälly palveluun.' },
        { q: 'Onko palvelu jo saatavilla?', a: 'Ei. Palvelu odottaa Traficomin ja vakuutusyhtiön kirjallista vahvistusta matkustajakuljetuksesta asiakkaan omalla autolla.' },
        { q: 'Sisältyykö lentoaseman jättömaksu hintaan?', a: 'Se mainitaan tarjouksessa erikseen, jos se koskee matkaasi.' },
      ],
    },
    en: {
      slug: 'airport-driver',
      nav: 'Airport driver',
      short: 'Airport',
      title: 'Own-car airport driver | DriveMe',
      description: 'Travel to or from Helsinki Airport in your own car, with your own luggage and child seats.',
      h1: 'Own-car airport driver',
      lead: 'Travel to or from the airport in your familiar vehicle, with luggage and child-seat setup already yours.',
      keywords: ['airport driver own car Helsinki', 'Helsinki airport own car transfer'],
      steps: [
        'You give the flight details, passenger count and luggage.',
        'We agree where the car and keys end after departure or begin before arrival.',
        'We confirm the driver, the schedule and the price.',
        'The driver takes you to the airport and handles the car as agreed.',
      ],
      included: [
        'Pre-booked driver and agreed support logistics',
        'Flight/time details',
        'Customer and vehicle handover according to the selected option',
        'Airport drop-off fees stated in the quote',
      ],
      customer: [
        'Provide accurate flight and luggage information',
        'Ensure the vehicle is suitable and legal',
        'Agree where the car and keys end after departure or begin before arrival',
        'Provide child seats and install them personally',
      ],
      excluded: [
        'Airport parking unless quoted',
        'Flight concierge or baggage handling',
        'Vehicle storage',
        'Traditional airport transfer in a DriveMe-owned car until that product is licensed and active',
      ],
      boundary: 'This is a launch gate, not an automatic launch item. We confirm no jobs before written regulatory and insurance clearance.',
      faq: [
        { q: 'Where does my car go while I fly?', a: 'It is agreed in the booking. The usual options are returning it to your home or an agreed address, or collecting it on your return day. Storage is not part of the service.' },
        { q: 'Is the service available now?', a: 'No. It awaits written Traficom and insurer confirmation on passenger transport in the customer’s own car.' },
        { q: 'Is the airport drop-off fee included?', a: 'It is stated separately in the quote when it applies to your journey.' },
      ],
    },
  },

  /* ------------------------------------------------------------------ */
  {
    key: 'business',
    category: 'business',
    launch: 'priority',
    appointment: 'depends',
    icon: 'business',
    price: { key: 'corporate' },
    related: ['relocation', 'dealer', 'workshop'],
    devNote: 'Lead form rather than instant checkout: company, Business ID, fleet size, monthly movements, common routes, service-level needs and invoice contact.',
    fi: {
      slug: 'yrityksille',
      nav: 'Yrityksille',
      short: 'Yrityksille',
      title: 'Yritysautojen siirtopalvelu ja fleet concierge | DriveMe',
      description: 'Ajoneuvojen noudot, huoltosiirrot, työntekijäluovutukset ja muut yritysautojen siirrot yhdeltä luotettavalta kumppanilta.',
      h1: 'Ajoneuvojen siirtopalvelu yrityksille',
      lead: 'Yksi luotettava yhteyshenkilö toistuviin ajoneuvosiirtoihin, huoltoaikoihin ja työntekijäluovutuksiin.',
      keywords: ['yritysautojen siirto', 'ajoneuvojen siirtopalvelu yrityksille', 'fleet concierge Finland'],
      steps: [
        'Kerrot kalustosi koon, tavallisimmat reitit ja kuukausittaisen siirtomäärän.',
        'Sovimme palvelutasosta, valtuutetuista tilaajista ja hyväksymisrajoista.',
        'Tilaukset tulevat yhdestä paikasta ja nimeämme kuljettajan jokaiseen työhön.',
        'Saat työkohtaisen tilatiedon ja kuukausittain koottavan laskun.',
      ],
      included: [
        'Nimetty yritysasiakkuus',
        'Keskitetty tilaus ja kuljettajan nimeäminen',
        'Ajoneuvon kunnon dokumentointi',
        'Kuukausittain koottu lasku',
        'Työkohtainen tila- ja poikkeamakirjaus',
      ],
      customer: [
        'Valtuutetut tilaajat ja kustannuspaikat',
        'Ajoneuvojen kelpoisuus ja palveluntarjoajien ajanvaraukset',
        'Selkeät hyväksymisrajat',
        'Ajantasaiset kalusto- ja yhteystiedot',
      ],
      excluded: [
        'Kaluston huoltopäätökset',
        'Kolmannen osapuolen työn laatu',
        'Hyväksymättömät korjauskulut',
        'Hinaus tai säilytys, ellei niistä ole erikseen sovittu',
      ],
      boundary: 'DriveMe hoitaa siirrot ja luovutukset. Huoltopäätökset, korjaushyväksynnät ja palveluntarjoajien laskut pysyvät yrityksen omissa käsissä.',
      faq: [
        { q: 'Mikä on pienin järkevä kalustokoko?', a: 'Palvelu on suunniteltu 2-50 auton kalustoille, joissa ei ole omaa kalustokoordinaattoria. Pienempikin onnistuu, jos siirtoja on säännöllisesti.' },
        { q: 'Saammeko yhden laskun?', a: 'Kyllä. Kokoamme kuukauden työt yhdelle laskulle kustannuspaikoittain eriteltynä.' },
        { q: 'Voiko työntekijä luovuttaa auton?', a: 'Kyllä, kun hänet on nimetty varauksessa valtuutetuksi luovuttajaksi tai vastaanottajaksi.' },
        { q: 'Hyväksyttekö korjauksia puolestamme?', a: 'Emme. Kuljettaja ei hyväksy töitä eikä kuluja. Hyväksymisrajaksi on asetettu 0 euroa, ellei sopimuksessa toisin sovita.' },
      ],
    },
    en: {
      slug: 'for-companies',
      nav: 'For companies',
      short: 'For companies',
      title: 'Corporate fleet concierge and vehicle movements | DriveMe',
      description: 'Vehicle collections, service transfers, employee handovers and other company car movements from one reliable partner.',
      h1: 'Vehicle movement service for companies',
      lead: 'One reliable contact for recurring vehicle movements, service appointments and employee handovers.',
      keywords: ['corporate fleet movements Finland', 'fleet concierge Helsinki'],
      steps: [
        'You tell us your fleet size, common routes and monthly movement volume.',
        'We agree service levels, authorised bookers and approval limits.',
        'Bookings come through one place and we assign a driver to every job.',
        'You get job-level status and one consolidated monthly invoice.',
      ],
      included: [
        'Named business account',
        'Central booking and driver assignment',
        'Vehicle condition documentation',
        'Monthly consolidated invoice',
        'Job-level status and exception record',
      ],
      customer: [
        'Authorised bookers and cost centres',
        'Vehicle eligibility and provider appointments',
        'Clear approval limits',
        'Accurate fleet and contact data',
      ],
      excluded: [
        'Fleet maintenance decisions',
        'Third-party workmanship',
        'Unapproved repair costs',
        'Towing or storage unless separately contracted',
      ],
      boundary: 'DriveMe handles the movements and handovers. Maintenance decisions, repair approvals and provider invoices stay with the company.',
      faq: [
        { q: 'What fleet size makes sense?', a: 'The service is built for fleets of 2-50 vehicles with no dedicated fleet coordinator. Smaller works too when movements are regular.' },
        { q: 'Do we get one invoice?', a: 'Yes. We consolidate the month’s jobs onto one invoice, itemised by cost centre.' },
        { q: 'Can an employee hand the car over?', a: 'Yes, when named in the booking as an authorised person.' },
        { q: 'Do you approve repairs for us?', a: 'No. Drivers approve no work and no cost. The approval limit is set to zero euro unless a contract says otherwise.' },
      ],
    },
  },
];

export const byKey = Object.fromEntries(services.map((s) => [s.key, s]));

/** Services offered in the "Take care of my car" path of the booking flow. */
export const conciergeKeys = services.filter((s) => s.category === 'concierge').map((s) => s.key);
/** Services offered in the "I need a driver" path. */
export const driverKeys = services.filter((s) => s.category === 'driver').map((s) => s.key);
