/**
 * The price request form in Swedish: every field, help text, error message and
 * the receipt the customer sees after sending.
 *
 * Keyed exactly like the Finnish and English blocks in build/booking-form.mjs
 * and merged into them there.
 */

import { WAITING } from '../../api/_lib/pricing.js';
import { brand } from '../site.mjs';

export const form = {
  typeLegend: 'Vilken flytt gäller det?',
  typeMove: 'Bilflytt',
  typeMoveSub: 'Flytt mellan verksamhetsställen, hemleverans, hämtning av inköpt bil eller en enskild flytt.',
  typeAppt: 'Serviceflytt',
  typeApptSub: 'Bilen till bokad service, besiktning, däckbyte eller tvätt och tillbaka igen.',
  typeJourney: 'Personlig förare',
  typeJourneySub: 'En förare kör dig och ditt sällskap i din egen bil.',
  moveService: 'Vilken typ av flytt?',
  moveServiceHelp: 'Valet styr offerten till rätt team. Detaljerna kan du precisera i meddelandefältet.',
  moveServiceNames: {
    branchTransfer: 'Mellan våra verksamhetsställen',
    homeDelivery: 'Hemleverans till kund',
    purchasedCarPickup: 'Hämtning av inköpt bil',
    relocation: 'En enskild flytt till en annan adress',
  },
  counterparty: 'Säljarens eller mottagarens kontaktuppgifter',
  counterpartyHelp: 'Namn och telefonnummer samt vem som får lämna ut eller ta emot bilen.',
  keyInstructions: 'Nycklar och tillträdesanvisningar',
  keyInstructionsHelp: 'Kod till nyckelskåp, väktare eller annan överenskommen praxis. Känsliga koder kan också ges per telefon.',
  customerTypeLegend: 'Vem begär offerten?',
  journeyLegend: 'Vart går resan?',
  journeyDestination: 'Destination',
  journeyDestinationHelp: 'T.ex. Helsingfors-Vanda flygplats, Tammerfors eller stugans adress.',
  passengers: 'Antal passagerare',
  passengersHelp: 'Föraren tar ingen plats: berätta hur många ni är som reser.',
  journeyReturn: 'Behöver du också en returresa?',
  businessNote: 'Företagskund: berätta om den första flytten här. Vi kommer överens om avtalspris och fakturering när vi ringer.',
  moveLegend: 'Vart ska bilen?',
  destination: 'Destinationsadress',
  returnLegend: 'Behövs en retur?',
  returnNo: 'Nej, bara en riktning',
  returnYes: 'Ja, bilen hämtas tillbaka senare',
  apptLegend: 'Tjänst och leverantör',
  service: 'Vilken tjänst ska bilen till?',
  serviceHelp: 'Annan destination? Välj "Kör min bil till en annan adress" ovan.',
  serviceNames: {
    inspection: 'Besiktning',
    workshop: 'Service eller verkstad',
    tyre: 'Däckbyte eller däckhotell',
    wash: 'Tvätt eller detaljrengöring',
    glass: 'Glas, plåt eller återkallelse',
    dealer: 'Bilhandel, leasing eller hyrfirma',
  },
  provider: 'Leverantör och adress',
  providerHelp: 'T.ex. besiktningsstationen eller verkstaden och dess adress. Tiden bokar du och tjänsten betalar du själv.',
  apptTime: 'Bokad tid, om den är känd',
  shape: 'Hur kommer bilen tillbaka?',
  shapeWait: 'Föraren väntar och kör tillbaka bilen',
  shapeWaitSub: `Väntetid högst ${WAITING.waitReturnIncludedMinutes} min.`,
  shapeReturn: 'Upphämtning och retur senare',
  shapeReturnSub: 'Vi kör tillbaka bilen när tjänsten är klar.',
  shapeOneWay: 'Bara dit',
  shapeOneWaySub: 'Du hämtar bilen själv eller så kommer vi överens om returen separat.',
  whereWhen: 'Upphämtning och tid',
  pickup: 'Upphämtningsadress eller postnummer',
  date: 'Önskad dag',
  window: 'Önskad tid',
  windowFlex: 'Flexibel',
  contact: 'Vem ringer vi?',
  name: 'Namn',
  phone: 'Telefon',
  email: 'E-post',
  emailHelp: 'Frivilligt. Vi skickar en bekräftelse om du anger en adress.',
  auth: 'Jag är bilens ägare eller innehavare, eller har rätt att överlämna bilen till DriveMes förare.',
  authLabel: 'Rätt att köra bilen',
  more: 'Mer information',
  moreSub: 'Frivilligt. Fyll i nu eller gå igenom dem när vi ringer.',
  plate: 'Registernummer',
  makeModel: 'Märke och modell',
  gearbox: 'Växellåda',
  manual: 'Manuell',
  automatic: 'Automat',
  fuel: 'Drivkraft',
  fuelPetrol: 'Bensin',
  fuelDiesel: 'Diesel',
  fuelHybrid: 'Hybrid',
  fuelEv: 'El',
  unknown: 'Vet inte',
  access: 'Anvisningar för infart och parkering',
  accessHelp: 'Port- eller dörrkod, våning i parkeringshuset, var nycklarna finns.',
  apptRef: 'Bokningsnummer',
  customerType: 'Kundtyp',
  person: 'Privatperson',
  company: 'Företag',
  companyName: 'Företagets namn',
  businessId: 'FO-nummer',
  invoiceEmail: 'E-post för fakturor',
  notes: 'Övrigt att beakta',
  notesHelp: 'Till exempel kända fel eller önskemål om retur till en annan adress.',
  laterNote: 'Registernummer, nyckelöverlämning, fullmakt, betalsätt och bokningsvillkoren går vi igenom före bekräftelsen.',
  terms: 'Servicevillkor',
  quote: 'Riktgivande pris',
  quoteNote: 'Priset inkluderar moms. Vi bekräftar ett fast DriveMe-pris före körningen. Leverantörens avgifter ingår inte.',
  quoteFrom: 'från',
  quoteManual: 'Fast offert',
  offerCode: 'Förmånskod',
  offerCodeHelp: 'Frivillig. Har du en kampanjkod skriver du in den här.',
  quoteManualNote: 'Det här uppdraget offererar vi för hand.',
  submit: 'Skicka prisförfrågan',
  submitting: 'Skickar…',
  errorTitle: 'Kontrollera de här punkterna',
  required: 'Den här uppgiften behövs.',
  badEmail: 'Kontrollera e-postadressen, eller lämna fältet tomt.',
  badPhone: 'Kontrollera telefonnumret.',
  badRange: 'Värdet ligger utanför det tillåtna intervallet.',
  mustAccept: 'Den här bekräftelsen behövs.',
  submitLocked: 'Innan du kan skicka förfrågan:',
  requiredNote: 'Fält märkta med * är obligatoriska. Att skicka förfrågan tar under en minut.',
  doneTitle: 'Tack - din prisförfrågan har kommit fram',
  doneBody: 'Det här är en förfrågan, ännu ingen bekräftelse. Vi ringer dig, går igenom bilens uppgifter och bekräftar förare, tid och ett fast pris.',
  doneCall: `Är det brådskande, ring ${brand.phone}.`,
  doneRef: 'Din referens',
  doneAgain: 'Skicka en ny förfrågan',
  failed: 'Förfrågan kunde inte skickas. Försök igen eller ring ' + brand.phone + '.',
  gatedTitle: 'Den här tjänsten går inte att boka ännu',
  gatedBody: 'Tjänsten är inte bokningsbar ännu. Vi berättar så snart den öppnar.',
  gateContactTitle: 'Kontakta oss',
  gateContactBody: 'Vi berättar gärna mer och hör av oss så snart tjänsten är tillgänglig.',
  lines: {
    base: 'Tjänstens grundpris',
    night: 'Nattillägg',
    weekend: 'Veckoslutstillägg',
    publicHoliday: 'Helgdagstillägg',
    urgent: 'Brådskandetillägg',
  },
};
